services:
  kafka-controller-1:
    image: apache/kafka:latest
    container_name: kafka-controller-1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - shared_network

  kafka-controller-2:
    image: apache/kafka:latest
    container_name: kafka-controller-2
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - shared_network

  kafka-controller-3:
    image: apache/kafka:latest
    container_name: kafka-controller-3
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - shared_network

  kafka-broker-1:
    image: apache/kafka:latest
    container_name: kafka-broker-1
    ports:
      - 9092:9092
      - 9093:9093
      - 9094:9094
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: PLAINTEXT://:19092,SASL_PLAINTEXT://:19093,SASL_SSL://:19094,PLAINTEXT_HOST://:9092,SASL_PLAINTEXT_HOST://:9093,SASL_SSL_HOST://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:19092,SASL_PLAINTEXT://kafka-broker-1:19093,SASL_SSL://kafka-broker-1:19094,PLAINTEXT_HOST://localhost:9092,SASL_PLAINTEXT_HOST://localhost:9093,SASL_SSL_HOST://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_SASL_PLAINTEXT_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_PLAINTEXT_HOST:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,SASL_SSL_HOST:SASL_SSL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_SSL_KEYSTORE_FILENAME: kafka-broker-1.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-broker-1-keystore-creds
      KAFKA_SSL_KEY_CREDENTIALS: kafka-broker-1-sslkey-creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka-broker-1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-broker-1-truststore-creds
      KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_LOG_DIRS: /var/lib/kafka/data/logs
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
    depends_on:
      - kafka-controller-1
      - kafka-controller-2
      - kafka-controller-3
    networks:
      - shared_network
    volumes:
      - ./config/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./secrets:/etc/kafka/secrets/
      - ./logs/kafka-broker-1:/var/lib/kafka/data/logs

  kafka-broker-2:
    image: apache/kafka:latest
    container_name: kafka-broker-2
    ports:
      - 9095:9095
      - 9096:9096
      - 9097:9097
    environment:
      KAFKA_NODE_ID: 5
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: PLAINTEXT://:19092,SASL_PLAINTEXT://:19093,SASL_SSL://:19094,PLAINTEXT_HOST://:9095,SASL_PLAINTEXT_HOST://:9096,SASL_SSL_HOST://:9097
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:19092,SASL_PLAINTEXT://kafka-broker-2:19093,SASL_SSL://kafka-broker-2:19094,PLAINTEXT_HOST://localhost:9095,SASL_PLAINTEXT_HOST://localhost:9096,SASL_SSL_HOST://localhost:9097
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_SASL_PLAINTEXT_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_PLAINTEXT_HOST:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,SASL_SSL_HOST:SASL_SSL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_SSL_KEYSTORE_FILENAME: kafka-broker-2.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-broker-2-keystore-creds
      KAFKA_SSL_KEY_CREDENTIALS: kafka-broker-2-sslkey-creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka-broker-2.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-broker-2-truststore-creds
      KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_LOG_DIRS: /var/lib/kafka/data/logs
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
    depends_on:
      - kafka-controller-1
      - kafka-controller-2
      - kafka-controller-3
    networks:
      - shared_network
    volumes:
      - ./config/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./secrets:/etc/kafka/secrets/
      - ./logs/kafka-broker-2:/var/lib/kafka/data/logs

  kafka-broker-3:
    image: apache/kafka:latest
    container_name: kafka-broker-3
    ports:
      - 9098:9098
      - 9099:9099
      - 9100:9100
    environment:
      KAFKA_NODE_ID: 6
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: PLAINTEXT://:19092,SASL_PLAINTEXT://:19093,SASL_SSL://:19094,PLAINTEXT_HOST://:9098,SASL_PLAINTEXT_HOST://:9099,SASL_SSL_HOST://:9100
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3:19092,SASL_PLAINTEXT://kafka-broker-3:19093,SASL_SSL://kafka-broker-3:19094,PLAINTEXT_HOST://localhost:9098,SASL_PLAINTEXT_HOST://localhost:9099,SASL_SSL_HOST://localhost:9100
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_SASL_PLAINTEXT_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_PLAINTEXT_HOST:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,SASL_SSL_HOST:SASL_SSL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-controller-1:9093,2@kafka-controller-2:9093,3@kafka-controller-3:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_SSL_KEYSTORE_FILENAME: kafka-broker-3.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-broker-3-keystore-creds
      KAFKA_SSL_KEY_CREDENTIALS: kafka-broker-3-sslkey-creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka-broker-3.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-broker-3-truststore-creds
      KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_LOG_DIRS: /var/lib/kafka/data/logs
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
    depends_on:
      - kafka-controller-1
      - kafka-controller-2
      - kafka-controller-3
    networks:
      - shared_network
    volumes:
      - ./config/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./secrets:/etc/kafka/secrets/
      - ./logs/kafka-broker-3:/var/lib/kafka/data/logs

  kafka-connect:
    image: debezium/connect:3.0.0.Final
    container_name: kafka-connect
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: kafka-broker-1:19093,kafka-broker-2:19093,kafka-broker-3:19093
      GROUP_ID: debezium-connect-group
      CONFIG_STORAGE_TOPIC: debezium-connect-configs
      OFFSET_STORAGE_TOPIC: debezium-connect-offsets
      STATUS_STORAGE_TOPIC: debezium-connect-status
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: false
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: false
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      PLUGIN_PATH: /kafka/connect
      CONNECT_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin";
      CONNECT_SASL_MECHANISM: PLAIN
      CONNECT_SECURITY_PROTOCOL: SASL_PLAINTEXT
      CONNECT_PRODUCER_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin";
      CONNECT_PRODUCER_SASL_MECHANISM: PLAIN
      CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_PLAINTEXT
      CONNECT_CONSUMER_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin";
      CONNECT_CONSUMER_SASL_MECHANISM: PLAIN
      CONNECT_CONSUMER_SECURITY_PROTOCOL: SASL_PLAINTEXT
    networks:
      - shared_network
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    volumes:
      - ./plugins:/usr/share/java

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    ports:
      - 8081:8081
    environment:
      - SERVER_PORT=8081
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_NAME=genius
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-broker-1:19093,kafka-broker-2:19093,kafka-broker-3:19093
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=PLAIN
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin";
    networks:
      - shared_network

networks:
  shared_network:
    external: true